### ISSUE TITLE
Add total slashing amount to subgraph

### ISSUE THREAD

**Issue by defi-lead** [powerpool-finance/powerpool-agent-v2-subgraph#24]
For Keeper add fields:
- Total slashed amount from this - we have this;
- Total slashed amount from others;
- Total slashed count from this
- Total slashed count from others;

**Comment by DeFIBrain88** [comment]
Total slashed amount from this - **slashedStake**
Total slashed amount from others - **getBySlashStake**
Total slashed count from this - **slashedStakeCounter**
Total slashed count from others - **getBySlashStakeCounter**

**Comment by DeFIBrain88** [comment]
https://github.com/powerpool-finance/powerpool-agent-v2-subgraph/pull/23
